### ISSUE TITLE
Request for StartIsBack++ support

### ISSUE THREAD

**Issue by Kajal4414** [YT-Advanced/SAB#1]
Dear Sir,

Thank you for this awesome script! It is working fine with the StartAllBack app, but I would appreciate it if you could update it to support StartIsBack++ as well. StartAllBack is only for Windows 11, so this would make your script more accessible to a wider range of users.

Thank you for your time and consideration.

**Comment by YT-Advanced** [comment]
Hi, in StartIsBack++, I found this dll, and it is safe when I decompiled it in JDA
https://drive.proton.me/urls/74TD6AD3Q0#juzk2ASJ2UGy
Download this dll and paste it into SIB folder
![image](https://github.com/YT-Advanced/SAB/assets/70064328/c4fe371d-95a1-426e-b613-8df35036d095)

**Comment by Kajal4414** [comment]
Thank you so much for providing the StartIsBack++ DLL file. It's working perfectly and I'm very grateful.
